### ISSUE TITLE
Support to install the SapMachine Version for the aarch64 (Apple Silicon) architecture

### ISSUE THREAD

**Issue by gregorwolf** [SAP/sapmachine-manager-for-macos#1]
Hello SapMachine Manager for MacOS Team,

is it planned to add support for the the aarch64 (Apple Silicon) architecture Version of SapMachine?

Best Regards
Gregor

**Comment by mthielemann** [comment]
This is already the case. SapMachine Manager downloads and installs only the versions of SapMachine for the architecture the Mac is running. So an an Intel Mac it installs the x86_64 version and on a Mac with Apple Silicon it installs the aarch64 version.

**Comment by gregorwolf** [comment]
Hi @mthielemann 

then I'm wondering why I run into this issue with the aarch64 version of the SAP Cloud Connector (https://tools.hana.ondemand.com/#cloud):

```
 sapcc-2.17.1-macosx-aarch64 which java
/usr/bin/java
➜  sapcc-2.17.1-macosx-aarch64 java --version
openjdk 21.0.4 2024-07-16 LTS
OpenJDK Runtime Environment SapMachine (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM SapMachine (build 21.0.4+7-LTS, mixed mode, sharing)
➜  sapcc-2.17.1-macosx-aarch64 ./go.sh 
using java /Library/Java/JavaVirtualMachines/sapmachine-21.jdk/Contents/Home/bin/java

Detected mismatch between jdk binaries for x86_64 and scc binaries for arm64
Stopping the process. Ensure to use the corresponding binaries either for x86_64 or for arm64
Set env variable NO_CHECK=1 to overcome this check
➜  sapcc-2.17.1-macosx-aarch64 /Library/Java/JavaVirtualMachines/sapmachine-21.jdk/Contents/Home/bin/java --version
openjdk 21.0.4 2024-07-16 LTS
OpenJDK Runtime Environment SapMachine (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM SapMachine (build 21.0.4+7-LTS, mixed mode, sharing
```

![image](https://github.com/user-attachments/assets/8e32b17d-63ea-459e-bcf6-249ea72f23ab)

Best Regards
Gregor

**Comment by mthielemann** [comment]
No idea. SapMachine Manger just downloads and installs the archive for the current architecture. If you see any issues with SapMachine you probably should reach out to the guys who are developing it. I just developed this tool and don't know much about Java or SapMachine in particular.

Regards,
Marc
