### ISSUE TITLE
Improve UX by adding + icon to install jre/jdk more easily

### ISSUE THREAD

**Issue by mehradrafigh** [SAP/sapmachine-manager-for-macos#2]
Hi all,

I switched from Cornetto to SAPMachine and saw this nitty app that enables me to easily switch between jdk version. I like that!
It would be great if there would be a + button that easily opens up the install view to install any supported jdk/jre version.

**Comment by mthielemann** [comment]
CMD+I can be used to install a new jvm. Does this help?

**Comment by mthielemann** [comment]
This will be available in the upcoming version 1.0.9 of _SapMachine Manager_.
